FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8012
CMD ["sh", "-c", "python manage.py migrate && python manage.py seed_books && python manage.py runserver 0.0.0.0:8012"]
