from django.db import models
from django.contrib.auth.hashers import make_password, check_password


class Manager(models.Model):
    """
    Manager model - higher level than staff
    Can view reports, manage staff, and oversee operations
    """
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    phone = models.CharField(max_length=20, blank=True)
    department = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'manager'
    
    def __str__(self):
        return self.name
    
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    
    def check_password(self, raw_password):
        return check_password(raw_password, self.password)


class Report(models.Model):
    """
    Business reports generated by managers
    """
    REPORT_TYPES = [
        ('sales', 'Sales Report'),
        ('inventory', 'Inventory Report'),
        ('customer', 'Customer Report'),
        ('staff', 'Staff Performance Report'),
    ]
    
    manager_id = models.IntegerField()
    report_type = models.CharField(max_length=50, choices=REPORT_TYPES)
    title = models.CharField(max_length=255)
    content = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'report'
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.title} ({self.report_type})"


class ManagerActivity(models.Model):
    """
    Log of manager activities
    """
    manager_id = models.IntegerField()
    action = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'manager_activity'
        ordering = ['-created_at']
    
    def __str__(self):
        return f"Manager {self.manager_id} - {self.action}"
